#!/bin/bash

# kill swap:
while read -r id;
do
  swapoff /dev/zram"$id"
  echo "$id" > /sys/class/zram-control/hot_remove
  echo "zram swap id$id removed" | systemd-cat -t zramservice -p info
done < /run/zramservice/swap

# now kill all other drives:
while read -r id;
do
  umount /dev/zram"$id"
  echo "$id" > /sys/class/zram-control/hot_remove
  echo "zram drive id$id removed" | systemd-cat -t zramservice -p info
done < /run/zramservice/mounts

# delete runtime directory
# rm -r /run/zramservice/